CREATE TABLE CountryCapital (
  Country VARCHAR(50),
  Capital VARCHAR(50)
);

INSERT INTO CountryCapital (Country, Capital) VALUES
  ('Afghanistan', 'Kabul'),
  ('Albania', 'Tirana'),
  ('Algeria', 'Algiers'),
  ('Andorra', 'Andorra la Vella'),
  ('Angola', 'Luanda'),
  ('Antigua and Barbuda', 'Saint Johns'),
  ('Argentina', 'Buenos Aires'),
  ('Armenia', 'Yerevan'),
  ('Australia', 'Canberra'),
  ('Austria', 'Vienna'),
  ('Azerbaijan', 'Baku'),
  ('Bahamas', 'Nassau'),
  ('Bahrain', 'Manama'),
  ('Bangladesh', 'Dhaka'),
  ('Barbados', 'Bridgetown'),
  ('Belarus', 'Minsk'),
  ('Belgium', 'Brussels'),
  ('Belize', 'Belmopan'),
  ('Benin', 'Porto-Novo'),
  ('Bhutan', 'Thimphu'),
  ('Bolivia', 'La Paz, Sucre'),
  ('Bosnia and Herzegovina', 'Sarajevo'),
  ('Botswana', 'Gaborone'),
  ('Brazil', 'Brasília'),
  ('Brunei', 'Bandar Seri Begawan'),
  ('Bulgaria', 'Sofia'),
  ('Burkina Faso', 'Ouagadougou'),
  ('Burundi', 'Bujumbura'),
  ('Cabo Verde', 'Praia'),
  ('Cambodia', 'Phnom Penh'),
  ('Cameroon', 'Yaoundé'),
  ('Canada', 'Ottawa'),
  ('Central African Republic', 'Bangui'),
  ('Chad', 'NDjamena'),
  ('Chile', 'Santiago'),
  ('China', 'Beijing'),
  ('Colombia', 'Bogotá'),
  ('Comoros', 'Moroni'),
  ('Congo (Democratic Republic of the)', 'Kinshasa'),
  ('Congo (Republic of the)', 'Brazzaville'),
  ('Costa Rica', 'San José'),
  ('Croatia', 'Zagreb'),
  ('Cuba', 'Havana'),
  ('Cyprus', 'Nicosia'),
  ('Czech Republic', 'Prague'),
  ('Denmark', 'Copenhagen'),
  ('Djibouti', 'Djibouti'),
  ('Dominica', 'Roseau'),
  ('Dominican Republic', 'Santo Domingo'),
  ('East Timor', 'Dili'),
  ('Ecuador', 'Quito'),
  ('Egypt', 'Cairo'),
  ('El Salvador', 'San Salvador'),
  ('Equatorial Guinea', 'Malabo'),
  ('Eritrea', 'Asmara'),
  ('Estonia', 'Tallinn'),
  ('Eswatini', 'Mbabane'),
  ('Ethiopia', 'Addis Ababa'),
  ('Fiji', 'Suva'),
  ('Finland', 'Helsinki'),
  ('France', 'Paris'),
  ('Gabon', 'Libreville'),
  ('Gambia', 'Banjul'),
  ('Georgia', 'Tbilisi'),
  ('Germany', 'Berlin'),
  ('Ghana', 'Accra'),
  ('Greece', 'Athens'),
  ('Grenada', 'Saint Georges'),
  ('Guatemala', 'Guatemala City'),
  ('Guinea', 'Conakry'),
  ('Guinea-Bissau', 'Bissau'),
  ('Guyana', 'Georgetown'),
  ('Haiti', 'Port-au-Prince'),
  ('Honduras', 'Tegucigalpa'),
  ('Hungary', 'Budapest'),
  ('Iceland', 'Reykjavik'),
  ('India', 'New Delhi'),
  ('Indonesia', 'Jakarta'),
  ('Iran', 'Tehran'),
  ('Iraq', 'Baghdad'),
  ('Ireland', 'Dublin'),
  ('Israel', 'Jerusalem'),
  ('Italy', 'Rome'),
  ('Jamaica', 'Kingston'),
  ('Japan', 'Tokyo'),
  ('Jordan', 'Amman'),
  ('Kazakhstan', 'Nur-Sultan'),
  ('Kenya', 'Nairobi'),
  ('Kiribati', 'Tarawa'),
  ('Korea (North)', 'Pyongyang'),
  ('Korea (South)', 'Seoul'),
  ('Kosovo', 'Pristina'),
  ('Kuwait', 'Kuwait City'),
  ('Kyrgyzstan', 'Bishkek'),
  ('Laos', 'Vientiane'),
  ('Latvia', 'Riga'),
  ('Lebanon', 'Beirut'),
  ('Lesotho', 'Maseru'),
  ('Liberia', 'Monrovia'),
  ('Libya', 'Tripoli'),
  ('Liechtenstein', 'Vaduz'),
  ('Lithuania', 'Vilnius'),
  ('Luxembourg', 'Luxembourg City'),
  ('Madagascar', 'Antananarivo'),
  ('Malawi', 'Lilongwe'),
  ('Malaysia', 'Kuala Lumpur'),
  ('Maldives', 'Male'),
  ('Mali', 'Bamako'),
  ('Malta', 'Valletta'),
  ('Marshall Islands', 'Majuro'),
  ('Mauritania', 'Nouakchott'),
  ('Mauritius', 'Port Louis'),
  ('Mexico', 'Mexico City'),
  ('Micronesia', 'Palikir'),
  ('Moldova', 'Chisinau'),
  ('Monaco', 'Monaco'),
  ('Mongolia', 'Ulaanbaatar'),
  ('Montenegro', 'Podgorica'),
  ('Morocco', 'Rabat'),
  ('Mozambique', 'Maputo'),
  ('Myanmar', 'Naypyidaw'),
  ('Namibia', 'Windhoek'),
  ('Nauru', 'Yaren District'),
  ('Nepal', 'Kathmandu'),
  ('Netherlands', 'Amsterdam'),
  ('New Zealand', 'Wellington'),
  ('Nicaragua', 'Managua'),
  ('Niger', 'Niamey'),
  ('Nigeria', 'Abuja'),
  ('North Macedonia', 'Skopje'),
  ('Norway', 'Oslo'),
  ('Oman', 'Muscat'),
  ('Pakistan', 'Islamabad'),
  ('Palau', 'Ngerulmud'),
  ('Panama', 'Panama City'),
  ('Papua New Guinea', 'Port Moresby'),
  ('Paraguay', 'Asunción'),
  ('Peru', 'Lima'),
  ('Philippines', 'Manila'),
  ('Poland', 'Warsaw'),
  ('Portugal', 'Lisbon'),
  ('Qatar', 'Doha'),
  ('Romania', 'Bucharest'),
  ('Russia', 'Moscow'),
  ('Rwanda', 'Kigali'),
  ('Saint Kitts and Nevis', 'Basseterre'),
  ('Saint Lucia', 'Castries'),
  ('Saint Vincent and the Grenadines', 'Kingstown'),
  ('Samoa', 'Apia'),
  ('San Marino', 'San Marino'),
  ('Sao Tome and Principe', 'São Tomé'),
  ('Saudi Arabia', 'Riyadh'),
  ('Senegal', 'Dakar'),
  ('Serbia', 'Belgrade'),
  ('Seychelles', 'Victoria'),
  ('Sierra Leone', 'Freetown'),
  ('Singapore', 'Singapore'),
  ('Slovakia', 'Bratislava'),
  ('Slovenia', 'Ljubljana'),
  ('Solomon Islands', 'Honiara'),
  ('Somalia', 'Mogadishu'),
  ('South Africa', 'Pretoria, Cape Town, Bloemfontein'),
  ('South Sudan', 'Juba'),
  ('Spain', 'Madrid'),
  ('Sri Lanka', 'Colombo, Sri Jayawardenepura Kotte'),
  ('Sudan', 'Khartoum'),
  ('Suriname', 'Paramaribo'),
  ('Sweden', 'Stockholm'),
  ('Switzerland', 'Bern'),
  ('Syria', 'Damascus'),
  ('Taiwan', 'Taipei'),
  ('Tajikistan', 'Dushanbe'),
  ('Tanzania', 'Dodoma'),
  ('Thailand', 'Bangkok'),
  ('Togo', 'Lomé'),
  ('Tonga', 'Nukuʻalofa'),
  ('Trinidad and Tobago', 'Port of Spain'),
  ('Tunisia', 'Tunis'),
  ('Turkey', 'Ankara'),
  ('Turkmenistan', 'Ashgabat'),
  ('Tuvalu', 'Funafuti'),
  ('Uganda', 'Kampala'),
  ('Ukraine', 'Kyiv'),
  ('United Arab Emirates', 'Abu Dhabi'),
  ('United Kingdom', 'London'),
  ('United States', 'Washington, D.C.'),
  ('Uruguay', 'Montevideo'),
  ('Uzbekistan', 'Tashkent'),
  ('Vanuatu', 'Port Vila'),
  ('Vatican City', 'Vatican City'),
  ('Venezuela', 'Caracas'),
  ('Vietnam', 'Hanoi'),
  ('Yemen', 'Sanaa'),
  ('Zambia', 'Lusaka'),
  ('Zimbabwe', 'Harare');

-- Retrieve all countries and their capitals
SELECT * FROM CountryCapital;