INSERT INTO Countries (CountryID, Country, CountryFlag) VALUES
  (1, 'Afghanistan', 'afghanistan.jpg'),
  (2, 'Albania', 'albania.jpg'),
  (3, 'Algeria', 'algeria.jpg'),
  (4, 'Andorra', 'andorra.jpg'),
  (5, 'Angola', 'angola.jpg'),
  (6, 'Antigua and Barbuda', 'antigua_and_barbuda.jpg'),
  (7, 'Argentina', 'argentina.jpg'),
  (8, 'Armenia', 'armenia.jpg'),
  (9, 'Australia', 'australia.jpg'),
  (10, 'Austria', 'austria.jpg'),
  (11, 'Azerbaijan', 'azerbaijan.jpg'),
  (12, 'Bahamas', 'bahamas.jpg'),
  (13, 'Bahrain', 'bahrain.jpg'),
  (14, 'Bangladesh', 'bangladesh.jpg'),
  (15, 'Barbados', 'barbados.jpg'),
  (16, 'Belarus', 'belarus.jpg'),
  (17, 'Belgium', 'belgium.jpg'),
  (18, 'Belize', 'belize.jpg'),
  (19, 'Benin', 'benin.jpg'),
  (20, 'Bhutan', 'bhutan.jpg'),
  (21, 'Bolivia', 'bolivia.jpg'),
  (22, 'Bosnia and Herzegovina', 'bosnia_and_herzegovina.jpg'),
  (23, 'Botswana', 'botswana.jpg'),
  (24, 'Brazil', 'brazil.jpg'),
  (25, 'Brunei', 'brunei.jpg'),
  (26, 'Bulgaria', 'bulgaria.jpg'),
  (27, 'Burkina Faso', 'burkina_faso.jpg'),
  (28, 'Burundi', 'burundi.jpg'),
  (29, 'Cabo Verde', 'cabo_verde.jpg'),
  (30, 'Cambodia', 'cambodia.jpg');